### PR TITLE
Fixes #7 - Change orange color in qualtrics to blue

### LINKED ISSUE #7: Change orange color in qualtrics to blue
It was requested that the orange color #bf5700 be changed to blue (#00274c) in qualtrics if it's easy/possible.

### PR DESCRIPTION
**Pull request by jonespm**
Changing this the correct way looks to require a webpack rebuild currently. This seems like the easiest fix. 

Maybe can try to discuss this upstream to get this fixed better.

### CODE REVIEW

**Comment by jonespm** [comment]
I put in a request to provide a alternate css file to override. I also think this would be better to just append this css text at the end of app.css. This would retain the orange in the footer for the branding. 

`.page_home .footer,.page_home .header{background-color:#00274c}.page_home .footer .float-right{background-color:#bf5700}`

image

**Comment by jonespm** [comment]
To test this just build it locally and check it out. You don't have to LTI launch.

`docker compose build;docker compose up`

Then go to http://localhost:8080/

The colors should be updated on the header and footer. I minified the custom.css styles, and retained the orange style in the footer. 

It's possible the branding logo could be targeted better in the css but this is working. I'm fine implementing any css suggestions!

**Review by lsloan — APPROVED** [review]
This seems straightforward.  It's great that the app already supports a custom CSS file.

I was wondering: Why was there a request to change the color from orange to blue?  Was it to improve accessibility or just to make it look more like a U-M site?

**Comment by jonespm** [comment]
It was from Dan to make it look more like U-M. 

Chris added this from my suggestion, it works pretty well.

**Pull request merged**
